# Generated by Django 3.0.2 on 2020-01-14 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('numberphone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=70)),
                ('isactive', models.BooleanField(default=True)),
                ('ban', models.BooleanField(default=False)),
                ('datecreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Сomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcomment', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbid', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.Client')),
                ('typeFeedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.FeedbackType')),
            ],
        ),
    ]
