# Generated by Django 3.0.2 on 2020-01-14 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='datecreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
