# Generated by Django 3.0.2 on 2020-01-14 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0003_сomment_datecreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameWork', models.CharField(max_length=50, verbose_name='Наименование работы')),
                ('description', models.CharField(max_length=250, verbose_name='Описание работы')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='feedbacktype',
            options={'verbose_name': 'Тип обратной связи', 'verbose_name_plural': 'Типы обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='сomment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='datecreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='textbid',
            field=models.CharField(max_length=200, verbose_name='Текст заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='typeFeedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.FeedbackType', verbose_name='Тип обратной связи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='client',
            name='datecreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=70, verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numberphone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='option',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='сomment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCHelp.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='сomment',
            name='datecreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='сomment',
            name='textcomment',
            field=models.CharField(max_length=200, verbose_name='Текст отзыва'),
        ),
    ]
