# Generated by Django 3.0.2 on 2020-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0004_auto_20200114_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
