# Generated by Django 3.0.2 on 2020-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0005_auto_20200126_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='unloadTelegram',
            field=models.BooleanField(default=False, verbose_name='Выгружена в телеграм'),
        ),
    ]
