# Generated by Django 3.0.2 on 2020-03-05 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0006_bid_unloadtelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('numberphone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=70, verbose_name='email адрес')),
                ('isactive', models.BooleanField(default=True, verbose_name='Активный')),
                ('ban', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('datecreation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCHelp.Roles', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
