# Generated by Django 3.0.2 on 2020-03-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0007_roles_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PCHelp.Staff', verbose_name='Ответственынй'),
        ),
    ]
