# Generated by Django 3.0.2 on 2020-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0008_bid_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='idtelegram',
            field=models.IntegerField(null=True),
        ),
    ]
