# Generated by Django 3.0.2 on 2020-03-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0009_staff_idtelegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='typeFeedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PCHelp.FeedbackType', verbose_name='Тип обратной связи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=70, null=True, verbose_name='email адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
