# Generated by Django 3.0.2 on 2020-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0010_auto_20200306_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.CharField(max_length=100, null=True, verbose_name='Обо мне'),
        ),
    ]
