# Generated by Django 3.0.2 on 2020-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCHelp', '0011_staff_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profileimg',
            field=models.CharField(default='profile.png', max_length=30, verbose_name='Фото'),
        ),
    ]
